# Generated by Django 4.0 on 2022-07-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_textes_remove_creneaux_typecreneau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textes',
            old_name='annonce',
            new_name='contenu',
        ),
        migrations.RemoveField(
            model_name='textes',
            name='informations',
        ),
        migrations.AddField(
            model_name='textes',
            name='nom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
