# Generated by Django 4.0 on 2022-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_inscription_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='csrf_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_demande',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='en_attente_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='reinitialisation_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creneaux',
            name='staff',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
