# Generated by Django 4.0 on 2022-07-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informations', models.TextField()),
                ('annonce', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='creneaux',
            name='typecreneau',
        ),
        migrations.AddField(
            model_name='creneaux',
            name='avec_commentaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creneaux',
            name='avec_inscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creneaux',
            name='text_bouton',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='typecreneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.creneaux'),
        ),
        migrations.DeleteModel(
            name='TypeCreneau',
        ),
    ]
