# Generated by Django 4.0 on 2022-07-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_annonce_textes_contenu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorisation',
            old_name='typecreneau',
            new_name='idcreneau',
        ),
    ]
