# Generated by Django 4.0 on 2022-07-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_typecreneau_autorisation_idcreneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneaux',
            name='staff',
            field=models.IntegerField(default=0),
        ),
    ]
