# Generated by Django 4.0 on 2022-07-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_creneaux_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='statut',
            field=models.CharField(default='', max_length=50),
        ),
    ]
