# Generated by Django 4.0.3 on 2022-07-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_utilisateur_csrf_token_utilisateur_date_demande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='information',
            field=models.BooleanField(default=True),
        ),
    ]
